### ISSUE TITLE
Installation to specific folder/module dependent on folder structure.

### ISSUE THREAD

**Issue by yapolyak** [scikit-build/scikit-build-core#406]
Hi,

I am trying to build a simple Python/C++ project using `scikit-build-core` and `pybind11`. Let's say I want my Python package to be called `myproject` and I am trying to install it with a submodule `binding` built from some bindings to a C++ code exposing a `CppClass`. Specifically, I want to be able to run `from myproject.binding import CppClass`.

By using [this](https://github.com/scikit-build/scikit-build-sample-projects/tree/master/projects/hello-pybind11) example I managed to make this happen by having the following folder structure:
```
.
 ├── CMakeLists.txt
 ├── README.md
 ├── include
 │   └── CppClass.h
 ├── pyproject.toml
 ├── src
 │   └── myproject
 │       ├── __init__.py
 │       └── bindings
 │           └── binding.cpp
 └── test_script.py
```
And by using the following CMakeList.txt:
```
cmake_minimum_required(VERSION 3.15...3.26)

project(${SKBUILD_PROJECT_NAME}
        VERSION ${SKBUILD_PROJECT_VERSION}
        LANGUAGES CXX)

find_package(Python REQUIRED COMPONENTS Interpreter Development.Module)
find_package(pybind11 CONFIG REQUIRED)

python_add_library(binding MODULE src/${SKBUILD_PROJECT_NAME}/bindings/binding.cpp WITH_SOABI)

target_link_libraries(binding
        PRIVATE
            pybind11::headers)

target_include_directories(binding
        PUBLIC
            include)

target_compile_definitions(binding
        PRIVATE
            VERSION_INFO=${PROJECT_VERSION})

target_compile_features(binding PRIVATE cxx_std_20)

install(TARGETS binding LIBRARY DESTINATION myproject)
```
However, this folder tree is not great, as I want `myproject` to look like a standard Python package with other pure Python modules. So I'd like `myproject` folder to be in the root folder, something like this:
```
.
├── CMakeLists.txt
├── README.md
├── include
│   └── CppClass.h
├── pyproject.toml
├── myproject
│   ├── __init__.py
│   └── bindings
│       └── binding.cpp
└── test_script.py
```
with the path in the CMakeLists.txt `python_add_library` command adapted accordingly (but `install` command left untouched).
Unfortunately, this doesn't work! Installation seems to run without any issue, but when I try to import `binding` from `myproject`, I am getting an `ModuleNotFoundError: No module named 'myproject.binding'` error message, coming from the `__init__.py` file. In both cases it looks as follows:
```
from .binding import CppClass

__all__ = ("CppClass",)
```

I wonder if this is `pybind11` -dependent issue, since in [this](https://github.com/scikit-build/scikit-build-sample-projects/tree/master/projects/hello-cpp) example, which doesn't use `pybind11`, such folder tree seems to work just fine! In that case, is there a workaround of that issue? Perhaps I could use `scikit-build` instead of `scikit-build-core` somehow to reach my goal?

Apologies for a lengthy issue description and thank you very much in advance for considering it!

**Comment by henryiii** [comment]
I would _highly_ recommend not losing the `src/` folder structure. It cases all sorts of errors and issues (last one I saw was... yesterday https://github.com/pypa/cibuildwheel/discussions/1530#discussioncomment-6254807. I've had to move existing packages to this to fix various errors long before scikit-build-core issues.) It's officially recommended for new Python projects at https://packaging.python.org/en/latest/tutorials/packaging-projects/?highlight=structure#a-simple-project. Both Python and pytest have bugs when it comes to mixing an installed library and one with the same name sitting in the CWD (python) or next to the test folder if it also has an `__init__.py` (pytest).

However, both scikit-build-core and pybind11 support non-src structure too. The problem you are seeing is Python adds the current working directory to the path, which breaks since the current working directory has a `binding/__init__.py`, so that takes priority over the installed `binding` package. On Python 3.11 or newer, you can set `PYTHONSAFEPATH` or pass `-P` when running python (see https://docs.python.org/3/using/cmdline.html#cmdoption-P). Otherwise, the root directory of your repository is invalid for running your package (any other directory should be fine).

For pytest, you'll also either need to avoid adding an `__init__.py` to your `tests` folder, or you'll need to make sure `--importmode=importlib` is always passed (so add it to your configuration, ideally in `pyproject.toml`). If you don't do that, it will prepend the test folder to the path, breaking you again. Personally, I avoid adding `__init__.py` to `tests` (as it can also cause problems with automatic test discovery in setuptools, maybe even adding a 'tests' package to your wheel! Though I think that's protected against these days.) Pytest 7 has a new `pythonpath` setting that can be used to add a "helper" or "plugin" directory that you can import from, which is better than making your tests folder a module with `__init__.py`.

This is all true for pure Python projects as well, it just happens that they _usually_ work when imported from the path. Things like importlib.metadata/importlib.resources might not - and really, you always want to test and run the same way your users will, but it _mostly_ works, so you might not have seen issues with loading this way. Yet.

But if you aren't working with a huge existing project that is stuck on a non-src layout due to how hard it would be to move, please use `src` layout! :)

**Comment by henryiii** [comment]
I believe hello-cpp happens to work because we never run it from the folder that contains the package, and the `tests` folder doesn't have an `__init__.py` file.

**Comment by yapolyak** [comment]
Thank you loads for such a prompt and informative response! Shame on me, I missed that modern Python projects should indeed use the `src` layout - indeed I might consider just using it!

However, I need to stress that importing did not work Not only from the main project folder - I changed directory away from it and got the same import error from my interpreter, even though I can see the project installed on pip list. So there must be something else getting in the way?

Also please ignore the test_script.py (I should've removed it from the tree I've shown) - I was actually testing imports by running an interpreter from command line.

**Comment by henryiii** [comment]
Is there a repo somewhere I can check? (Though what I'd do is build a wheel and then use `unzip -l thing.whl` to see where the `.so` is going).

**Comment by yapolyak** [comment]
Unfortunately no - I also had to modify some names as it is a closed-source project, apologies! I could of course reconstruct something simple, but tbh I am just thinking to accept the `src` structure - in fact I am grateful you pointed me to it!

I did want to take a look at the wheel indeed but so far did not find (perhaps did not look carefully) how to build one with scikit-build-core :D But you are right, I just needed to check my env's `site-packages`! I will update you if I figure something out!

**Comment by yapolyak** [comment]
Hmm, it is in the core project folder: site-packges/myproject/binding.cpython-39-darwin.so - together with the `__init__.py`. So should work, but perhaps it is indeed Python's issue with paths after all...

**Comment by henryiii** [comment]
Maybe you were running a script? `python dir/something.py` injects `dir` at the top of the path.

**Comment by yapolyak** [comment]
No, I was just opening interpreter by running `python` and typing `from myproject import binding.CppLibrary` inside... Or even simply `import myproject`.

But, really, you are completely right, and I should just adopt the `src` structure - I don't see it as a problem anymore, so for my purpose I think the issue is resolved! Thank you very much indeed!

**Comment by yapolyak** [comment]
Btw I've checked https://github.com/scikit-build/scikit-build-sample-projects/tree/master/projects/hello-pybind11 again, and I am somewhat puzzled how `hello.hello()` works there, while you install like this:
```
install(TARGETS ${python_module_name} DESTINATION .)
```
not
```
install(TARGETS ${python_module_name} DESTINATION hello)
```
Perhaps I am still misunderstanding how this works...

**Comment by henryiii** [comment]
That's a scikit-build (classic) example, not scikit-build-core. Scikit-build-core requires you to be explicit about package directories - based on all the issues from scikit-build (classic) with the "feature". You can simulate it in scikit-build-core though by setting `[tool.scikit-build] wheel.install-dir = "hello"` explicitly.

**Comment by LecrisUT** [comment]
It took me a while to understand the structure as well. Basically `install(DESTINATION)` is relative to top level python source, e.g. `site-packages` folder. So you can install in any package/sub-package you want.

Second key point is that the cython/pybind library etc. are modules themselves. Think of how you have `my_pkg/moduleA.py` is imported like `import my_pkg.moduleA`, a file `my_pkg/my_bindings.cpython-39-darwin.so` becomes `import my_pkg.my_bindings`. Granted the example given is a bit weird because it's installed as a global module, not as a module within a package (i.e. strip the `my_pkg`).

Hope this can clear out some confusion.

**Comment by yapolyak** [comment]
I need to update  (and resolve) this thread, as I figured out that, apparently, the issue must have been in me somehow previously messing up with the `site-packages` folder of my environment. I noticed that there I had a `/bindings` folder (empty), and when I deleted it and reinstalled `myproject` using the second (`src`-less) layout - the import worked just fine... Apologies for not figuring this out previously - I think I must have somehow achieved this mess by playing with installing to `.` in the project folder, and by moving it later as described here (but with various ad-hock modifications): https://github.com/scikit-build/scikit-build-sample-projects/blob/52f172abac47798dbedcdf2a35d6e2833f2c1ad2/projects/hello-cmake-package/CMakeLists.txt#L101

In any case, this discussion was very useful - I learned a lot, and will now most probably adopt the `src` layout (which seemed to actually defend against this issue in any case).

**Comment by LecrisUT** [comment]
Depends on what is your criteria for relocatable. Simply removing `RPATH` should be ok as it will use whichever paths you have on the system or `(DY)LD_LIBRARY_PATH`. If instead you want it to always link to the library that you bundle to (not the binding library, but whichever other libraries you build in cmake), then you would need to add the RPATH of the final installation directory. For that, the example should still work, but maybe you have to play around with the prefix set there.
