### ISSUE TITLE
Install does not preserve symlink

### ISSUE THREAD

**Issue by LecrisUT** [scikit-build/scikit-build-core#492]
Just quickly writing the issue before looking more carefully. Basically I've noticed that at least on `muslinux`, the symlinks are not maintained and instead the linked files are copied

```dockerfile
FROM python:alpine

RUN apk update
RUN apk add musl-dev gcc linux-headers cmake neovim bash
RUN pip install spglib
```

**Comment by henryiii** [comment]
Symlinks are not supported by CPython’s standard library in zipfile. Wheels are just zip files.

**Comment by LecrisUT** [comment]
Hmm, bummer. Zip files themselves support symlinks though right? Is https://github.com/python/cpython/issues/107845 supposed to fix that, or that is just for the build and not for the archiving?

**Comment by henryiii** [comment]
That’s tarfile (and security related). The issue is with zipfile, tarfile does support them. There’s a 10+ year old bug report about it somewhere. Now that windows simlink support is a lot better, I think it should be revisited. But it hasn’t afaik.

I’ve also seen a third-party library that support symlinks in zipfiles. But pip doesn’t use it.

pep 660 mentions this bug.

**Comment by henryiii** [comment]
There are older issues, but this seems to be the tracking issue: https://github.com/python/cpython/issues/82102

Looks like it was on hold until security issues could be worked out with tar file. But I think those were worked out.

**Comment by LecrisUT** [comment]
Should be supported automatically when that issue is resolved right?
