### ISSUE TITLE
Migrating custom setup.py logic

### ISSUE THREAD

**Issue by dokempf** [scikit-build/scikit-build-core#521]
Thanks for this great project, my first migration was a 5 minute job - absolutely wonderful experience.

On the second project, I am facing an issue with a `setup.py` file that contains actual logic of the following form:

```
try:
    import mpi4py

    cmake_args.append(f"-DMPI4PY_INCLUDE_DIR={mpi4py.get_include()}")
except ImportError:
    pass

setup(
    ...
    cmake_args=cmake_args,
)
```

Is there any chance of translating this into scikit-build-core?

FWIW: This is the full setup.py: https://github.com/parafields/parafields/blob/main/setup.py

**Comment by LecrisUT** [comment]
[This PR](https://github.com/scikit-build/scikit-build-core/pull/514) is close to making this feature available. The catch is that there is no support against checking installed modules. But that might not be included because the wheel package cannot contain variants of the python package like in conda. Consider this scenario:
- Wheel package or local pip install is built with/without mpi4py
- The user then removes/installs mpi4py from the environment
- The binary may no longer be executable depending on the python interface checks or may not include any mpi capablities, until the package is rebuilt

Instead try to make the python module (and C/C++ libraries) dynamic in their mpi dependence e.g.:
- common top-level C/C++ interface + library and separate libraries for serial and mpi that are dynamically loaded and configured via environment/configure files
- common top-level C/C++ interface only and thin wrappers over the mpi interface that lead to no-op on serial execution. In this case the python interface can load either variant using `ctypes.dll.LoadLibrary`/`LD_LIBRARY_PATH`/`RPATH`, etc.
- parallel installation of both variants, where the loading of the python bindings is dynamically controlled according to what is installed

Probably the simplest implementation would be the second and third one depending on if the SONAME is the same or not.

On the CMake implementation side, you can simply add a guard against `SKBUILD` and dynamically load the appropriate libraries inside there, e.g. writing a think `FindMPI4PY.cmake` (but please namespace the module otherwise it would clash with other people's implementation) that calls appropriate python commands to get the include/library locations. Overall this is the preferred approach because it can make the build/install process independent of `skbuild-core`, e.g. if you need to debug in the C/C++ IDE.

**Comment by henryiii** [comment]
It's worse that just that. I expect that custom logic predates PEP 517/518. Packages are now built in an isolated environment. That means the _only_ dependencies the build process sees are the ones in the build requirements. If `mpi4py` is listed there, then it will be _always_ built against, and if it's not, it will _never_ be built against - even if it's locally installed.

Now, if you either don't distribute wheels, or only use MPI on custom builds, and you build your MPI enabled wheels with build isolation off, then you can just move the logic into CMake. Do this:


```cmake
# After find_package(Python ...)
execute_process(
  COMMAND
    ${Python_EXECUTABLE} -c
    "import mpi4py; print(mpi4py.get_include(), end='')"
  RESULT_VARIABLE RESULT_PRESENT
  OUTPUT_VARIABLE _MPI4PY_INCLUDE_DIR
  ERROR_QUIET)
if(RESULT_PRESENT STREQUAL "0")
  set(MPI4PY_INCLUDE_DIR _MPI4PY_INCLUDE_DIR CACHE FILEPATH "")
endif()
```

FYI, if you use pybind11, it adds this helper:

```cmake
pybind11_find_import(mpi4py [VERSION <number>] [REQUIRED] [QUIET])
```

Though you'd still need to execute Python to get the include, so you are better off doing it manually as shown above.

If you support building without scikit-build, you can protect with `if(DEFINED SKBUILD)` as mentioned above if you want to keep this manual.

---

If you don't care about making it automatic, though, as a user already has to disable build isolation to use it, then you could also just pass `-Ccmake.define.MPI4PY_INCLUDE_DIR=...` when building, too.

---

FYI, longer term, we'll add support for adding custom flags, and probably some support for custom logic. Those won't fix the issues with this, though, they will only make it a bit easier to get a nicer interface for building with different options.

**Comment by dokempf** [comment]
Thanks a lot for your answers, I think my best bet is indeed to move the logic into CMake!

> It's worse that just that. I expect that custom logic predates PEP 517/518. Packages are now built in an isolated environment. That means the _only_ dependencies the build process sees are the ones in the build requirements. If `mpi4py` is listed there, then it will be _always_ built against, and if it's not, it will _never_ be built against - even if it's locally installed.

In my particular case I do have it in build requirements, but I am patching out this requirement in order to build sequential wheels for all platforms including Windows - it is a bit of a wild hack.

**Comment by henryiii** [comment]
Assuming this is resolved! Let me know if not.
