### ISSUE TITLE
Build failure with CMake 3.28 on MacOS

### ISSUE THREAD

**Issue by dokempf** [scikit-build/scikit-build-core#574]
I am unsure whether this is an issue with scikit-build-core or with the CMake Python distribution or with CMake itself, but my MacOS CI pipelines started failing suddenly and I identified that the CMake 3.28 has been released in the mean time. Reverting to `3.27.x` fixes the issue.

The error logs are quite cryptic - they print the C++ compiler and then suddenly stop without any further error message: https://github.com/3dgeo-heidelberg/py4dgeo/actions/runs/7222320112/job/19679082470#step:8:620

I have currently no idea what is causing this, but I am happy to have found a workaround. If you have any ideas or need further information, I am happy to help.

**Comment by LecrisUT** [comment]
The error seems to be with the project [`py4dgeo`](https://github.com/3dgeo-heidelberg/py4dgeo), so if you can get a more detailed log of that project, that would help. Indeed it seems rather weird how this failed at:
```
Detecting CXX compiler ABI info
```
Especially since the previous step succeeded. Can you try a few things?
- Use [`lukka/get-cmake`](https://github.com/lukka/get-cmake) and try with specific versions of CMake? Specifically, try `3.28.1`
- Try other versions of `runs-on: macos`
- Is is python version specific? Could you enable all of your other runners via `matrix.strategy.fail-fast = false`?

**Comment by dokempf** [comment]
Thanks for pointing me towards `lukka/get-cmake`. It allowed me to easily debug with the CMake versions and indeed this was caused by a segmentation fault introduced in v3.28.0 and fixed in v3.28.1! Let's hope for a quick Python release of 3.28.1!

**Comment by henryiii** [comment]
We can yank 3.28.0 as a stopgap too.

**Comment by henryiii** [comment]
@jcfr @thewtex I don’t seem to have permissions, can you yank 3.28.0?

**Comment by jcfr** [comment]
> re: yanked

All set.

![image](https://github.com/scikit-build/scikit-build-core/assets/219043/d8a1e61b-ff0a-4aed-bb7d-272bff78251c)

**Comment by henryiii** [comment]
Fantastic, thanks! We will get out the CMake release as soon as possible.
