### ISSUE TITLE
The capital letters in the project names.

### ISSUE THREAD

**Issue by hzhangxyz** [scikit-build/scikit-build-core#575]
My project.name contains both capital letters and lowercase letters, but scikit-build-core generate the wheel, which name is all lowercase.

**Comment by henryiii** [comment]
The name is preserved in the metadata exactly as you requested it, but the wheel names are normalized. You can't have some valid name characters (like "-" or ".") in a wheel name.

**Comment by hzhangxyz** [comment]
> The name is preserved in the metadata exactly as you requested it, but the wheel names are normalized. You can't have some valid name characters (like "-" or ".") in a wheel name.

I did not use some special char, just "PyTAT", that is the name of my project, it works well when using setuptools, but normalized after switching to sk build core.

**Comment by henryiii** [comment]
All backends except setputools normalize the filenames (at least I was told that when I was requested by the PyPI folks to add file normalization, I haven't checked all of them). Setuptools wants to too, I think, but it's hard to change it for back compat reasons.

You can rename the file after producing it and before uploading to PyPI if you want, though - since it's case insensitive, just changing the case of the name is safe and doesn't require using `wheel tags`.

**Comment by hzhangxyz** [comment]
> All backends except setputools normalize the filenames (at least I was told that when I was requested by the PyPI folks to add file normalization, I haven't checked all of them). Setuptools wants to too, I think, but it's hard to change it for back compat reasons.

OK, it seems my fault to use captical letter in the name.

**Comment by henryiii** [comment]
That’s fine, it will show up on the PyPI page exactly as you prefer, it’s just the file that should be normalized. MacOS and Windows are case insensitive already, so this keeps a single reliable file name on all systems.
