### ISSUE TITLE
Using dependency from parent folder or changing project root to parent folder

### ISSUE THREAD

**Issue by dudoslav** [scikit-build/scikit-build-core#581]
Hello,

I am a bit stuck with using scikit-build-core in our project, since it requires us to have all python logic in a different folder to the actual library code:
```
.
├── apis
│   └── python
│       ├── CMakeLists.txt
│       └── pyproject.toml
└── lib
    └── CMakeLists.txt
```

The issue here is that the `pyproject.toml` needs to run the `lib/CMakeLists.txt` (this one is the main one and uses `add_subdirectory(../apis/python)`). However, this breaks the sdist builds. Is there a way to make scikit-build-core change its root folder to parent folder, for example with some `project.root` option? This would fix all of these issues. Note that we really prefer not to move pyproject.toml to a different folder. This is a large project with bindings for multiple languages not just Python.

Anyway, thank you very much for your time :)

**Comment by LecrisUT** [comment]
You can do either of:
- move `pyproject.toml` to the root. Make sure you alter `wheel.packages` accordingly
- change `cmake.source-dir` to the top level, but you are reporting that

  > However, this breaks the sdist builds.

  This is odd. Afaiu, the `sdist` would still contain the full git archive, but maybe `pip` would not know where to get the `pyproject.toml`. What error do you have specifically? Is it with `pip` or with `cmake` side? This must be possible since projects like `hatch`/`hatchling` have multiple `pyproject.toml`, and their `sdist` is simply the subfolder where the `pyproject.toml` is located. It would be tricky to design the import of `lib`, but it would still be possible if you design `apis/python` as a standalone importable project using `FetchContent`.

But, I would say, having only `pyproject.toml` and similarly other such packaging metadata files like node's `project.json` on the top-level root is not a bad idea, since there are other tools that utilize it automatically like GitHub's dependency graph.

**Comment by dudoslav** [comment]
Thank you very much for reply,

I completely agree with your point that having `pyproject.toml` or `project.json` top-level is a good idea. However, I am still exploring that option of having it separately inside of its project. So, here is the issue:

Since the main CMakeFile is outside of pyproject's folder structure (`../../src`) it is not included in the sdist package. So after I try install the sdist package I get an error:

```
      scikit_build_core.errors.CMakeConfigError: source directory ../../src does not exist
```

So, CMake error.

**Comment by LecrisUT** [comment]
Ok, it seems that the `sdist` is just the subdirectory that contained the `pyproject.toml`, and I don't think there would be `pip` native way to have `pyproject.toml` in a subfolder of the `sdist.

In this case, your other option is to make the `api/python` project be buildable as a standalone project. A few notes on how to achieve this:
- `api/python` should import the main project via `FetchContent(FIND_PACKAGE_ARGS)` so that it can be imported both as `find_package` or as a `FetchContent` (latter one is important to have the `sdist` be buildable in any environment). This is also dependent on how you want to link to the main project, i.e. via shared or static library (for the latter use only `FetchContent`)
- main project can conditionally `add_subdirectory` the relevant api (in order to support non-scikit-build builds), but beware of the scoping differences when calling one from another
- setup the `pyproject.toml` so that the `sdist` build sets any relevant options for `find_package`/`FetchContent`, e.g. the git commit that it should checkout
