### ISSUE TITLE
Is it possible to include a file from the parent folder in the sdist via sdist.include ?

### ISSUE THREAD

**Issue by maximiliank** [scikit-build/scikit-build-core#615]
In case of a non-root folder python project, e.g. 
```
.
├── python
│   ├── CMakeLists.txt
│   └── pyproject.toml
│   └── src
└── cpp
    └── CMakeLists.txt
```

Would it be possible to include the `cpp` via `sdist.include = ["../cpp"]`? If I try it out it is not included.

This would help to create a sdist including all relevant file which are required to build the package. I tried doing it via cmake, but there I only found a way to copy the relevant files to `${CMAKE_CURRENT_SOURCE_DIR}` but I would like to avoid polluting the source tree.

Is there any way to achieve this?

**Comment by LecrisUT** [comment]
Iiuc, `sdist` will always have the format starting from `pyproject.toml` outwards, i.e. we would not have a way to populate directories beneath that level. Generally it would be better to move the `pyproject.toml` to top-level so that the full project can be built, unless `/python` is buildable as an independent project.

In the meantime, maybe what you could do is have symbolic links (iirc, the symlinks are de-linked when creating sdist).

**Comment by maximiliank** [comment]
If I add a link it works and the folder is then included in the sdist. I understand that once cannot populate directories beneath that level, but would it be possible to copy during the sdist package creation data from the parent folder into the sdist package, e.g. including the `cpp` folder in the sdist? Of course, then I would need to adjust the cmake scripts such that it can work in this way as well.

I agree with you, putting the `pyproject.toml` into the root is much more straight forward.

**Comment by henryiii** [comment]
I believe this was discussed somewhere, I think the plan is to eventually have a force-include option, mirroring the one in Hatch.
