### ISSUE TITLE
Citation information for skbuild-core

### ISSUE THREAD

**Issue by inakleinbottle** [scikit-build/scikit-build-core#738]
I'm using scikit-build-core in a large package, and I'm currently writing a paper about this. Does scikit-build-core have preferred bibliographic data for citing the project in publications. If so, can these be provided here.

**Comment by henryiii** [comment]
@jcfr, @thewtex, should we add Zenodo?

**Comment by jcfr** [comment]
Instead, what about adding `CITATION.cff`[^1] with one of the publication listed at https://github.com/scikit-build/scikit-build?tab=readme-ov-file#publications ? 

Alternatively, we could also wait to have the proceeding for SciPY 2024, I am tentatively to have it done before the deadline (May 26th)

[^1]: https://citation-file-format.github.io/

**Comment by jcfr** [comment]
Since the first talk referenced at https://github.com/scikit-build/scikit-build?tab=readme-ov-file#publications is specific to scikit-build "classic", I think we should reference the second link.

Or is there a more recent scikit-build-core talk for which we could generate a zenodo and then reference in a `CITATION.cff` ? 

Alternatively, we could:
- submit an entry to https://joss.theoj.org/ 
- generate zenodo from the `scikit-build-core` repository itself[^1]

[^1]: I would prefer to avoid this as we will soon have an actual proceeding or we may already have a more recent talk to reference.

**Comment by inakleinbottle** [comment]
CITATION.cff seems to be the correct solution to this. The paper I wanted the citation for is for SciPy 2024 :)

**Comment by henryiii** [comment]
Our SciPy 2024 is what we want to use for the citation. 😆 Can you cite a paper in the same conference? 😜

**Comment by jcfr** [comment]
For reference:
* https://github.com/scipy-conference/scipy_proceedings/pull/939

**Comment by cbcunc** [comment]
Consider that a reference to this repository  as a citation may be more useful than a reference to a paper about this repository. Does this repository have a DOI?

**Comment by henryiii** [comment]
NO, I think that would have been done with Zenodo, https://github.com/scikit-build/scikit-build-core/issues/738#issuecomment-2110522206, to which @jcfr replied https://github.com/scikit-build/scikit-build-core/issues/738#issuecomment-2110645795.
