### ISSUE TITLE
How to run ```make test``` equivilent after buiilding wih scikit build core

### ISSUE THREAD

**Issue by shimwell** [scikit-build/scikit-build-core#830]
I'm attempting to make use of scikit build core on [openmc](https://github.com/openmc-dev/openmc/pull/3087) which currently has a two stage build process (```cmake``` and ```pip```)

Currently in the CI the package is build with ```cmake ..``` then tested with ```make test```

Is there a way of running the equivalent of [ this make test ](https://github.com/openmc-dev/openmc/blob/0ad003307a67e5eb6c161fed2f3c6b571649de79/.github/workflows/ci.yml#L149-L150)  command when the package has been built with scikit build core?

**Comment by LecrisUT** [comment]
I would first question what is `make test` supposed to test. If you run it inside the build environment it does not pick up the post installation files (e.g. the python files), and by the time you make it work without it, you end up being able to simply run `ctest` without `scikit-build-core`. If you run it outside than you can simply run `pip install -e` and then do some standard `pytest`.

My approach is to have both a `ctest` and a `pytest` runner that complement each other, rather than trying to maneuver around having everything in one.

**Comment by henryiii** [comment]
I would second that, if you have pure compiled tests, you should probably build outside of scikit-build-core and run those tests. You should also have pytest tests that run with the installed package.

but yes, what’s your describing is actually a build target, and we support specifying build targets.
