### ISSUE TITLE
Issues when building a conda package

### ISSUE THREAD

**Issue by vigneshmanick** [scikit-build/scikit-build-core#863]
I am testing building a conda package with scikit-build-core and have started with the pybind example and have run into some issues

### Issues

1. The necessary packages that are automatically installed and injected into the environment (cmake, ninja, setuptools_scm etc.) doesn't seem to work when running with conda build.  
2. When running the example on a local machine that has no cmake installed, the build errors out with `cmake not found`. This is working in the github pipeline since the github runners already have cmake installed. i.e cmake is missing from the build section in the recipe
3. The build also doesn't run in parallel even if ninja is set in the host/build section. The env variable `CMAKE_BUILD_PARALLEL_LEVEL` needs to be set.

There could be other discrepancies but these are the most prominent ones that i found 

### Reproducilbe example

```bash
git clone https://github.com/pybind/scikit_build_example.git
conda create -n cb conda-build conda-verify pytest
conda activate cb && cd scikit_build_example && conda build conda.recipe
# errors because cmake is not found
# after cmake is defined in the build section, the compiling is run in serial
```

any pointers on what need to be set for a conda build process to work similar to usual `pip install . ` with scikit build core would be very helpful.

Thanks!

**Comment by henryiii** [comment]
We need more docs on setting up Conda-build. The rules:

* Conda builds are made in conda environments, so you have to set them up manually in your recipe.
* You must add a dependency on cmake. The scikit-build-core package can't depend on cmake due to conda limitations.
* You either have to have a dependency on make, or you have to unset `CMAKE_GENERATOR` or set it to `"Ninja"`. conda-build hard-codes it to make even if make is not present. If you use make, then it will build on one core unless `CMAKE_BUILD_PARALLEL_LEVEL` is set. Ninja multithreads automatically.

**Comment by henryiii** [comment]
And examples are at https://github.com/search?type=code&q=org%3Aconda-forge+path%3Arecipe%2Fmeta.yaml+scikit-build-core

**Comment by henryiii** [comment]
Oh, that's the pybind/scikit_build_example, it's missing these parts, that's embarrassing...

**Comment by vigneshmanick** [comment]
Thanks for the quick response, this works!
