### ISSUE TITLE
Issues with Shared Library Linking and Including OpenBLAS in PyPI Package

### ISSUE THREAD

**Issue by r1cheu** [scikit-build/scikit-build-core#905]
Hi there,

I'm currently working on a project that leverages [Armadillo](https://arma.sourceforge.net/), [Carma](https://carma.readthedocs.io/en/latest/introduction.html), and [pybind11](https://pybind11.readthedocs.io/en/stable/). I started from the [scikit_build_example](https://github.com/pybind/scikit_build_example) repository, but I'm facing a couple of challenges during the build process with CMake and `pip install`.

#### 1. Issue with Linking to `libarmadillo.so`
When building with CMake directly, the `_core.cpython-312-x86_64-linux-gnu.so` is correctly linked to `libarmadillo.so.14`. However, this linking is not occurring when using `pip install` during the distribution process. Below is my current `CMakeLists.txt`:

```cmake
# policies up to CMake 3.27
cmake_minimum_required(VERSION 3.15...3.30)

# Scikit-build-core sets these values for you, or you can just hard-code the
# name and version.
project(
  ${SKBUILD_PROJECT_NAME}
  VERSION ${SKBUILD_PROJECT_VERSION}
  LANGUAGES CXX)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

set(PYBIND11_FINDPYTHON ON)
find_package(pybind11 CONFIG REQUIRED)

include(FetchContent)
FetchContent_Declare(
    Armadillo
    GIT_REPOSITORY https://gitlab.com/conradsnicta/armadillo-code.git
    GIT_TAG        40d2d9fb9c148e1caff20bad5d2cde2e9bf73005) # 14.0.2
FetchContent_Declare(
    carma
    GIT_REPOSITORY https://github.com/RUrlus/carma
    GIT_TAG 7a8fbbea1b1febbb7b4462d8217c2bc84cd31ba4) # 0.8.0

FetchContent_MakeAvailable(Armadillo carma)
find_package(OpenMP)

include_directories(${PROJECT_SOURCE_DIR}/include)

# Create an interface library for common dependencies
add_library(cpp_lib INTERFACE)
target_link_libraries(cpp_lib INTERFACE armadillo OpenMP::OpenMP_CXX)
add_library(py_lib INTERFACE)
target_link_libraries(py_lib INTERFACE pybind11::module carma::carma)

add_library(core src/core.cpp)
target_link_libraries(core PRIVATE cpp_lib)

pybind11_add_module(_core MODULE bindings/bind_core.cpp)
target_link_libraries(_core PRIVATE core py_lib)

# The install directory is the output (wheel) directory
install(TARGETS _core LIBRARY DESTINATION .)
```

**Questions:**
1. I’ve tested static linking, and it works fine. However, is there a way to properly use shared libraries (`libarmadillo.so`) and ensure it’s linked correctly during `pip install`?
   
2. The second problem involves `OpenBLAS`. How do I include `libopenblas.so` in my package and ensure it is correctly linked, whether I am building the wheel in CI or manually via `pip install` (either through wheels or `sdist`)?

Any help would be appreciated, especially on how to resolve these issues with shared library linking and packaging OpenBLAS!

Thanks in advance!

**Comment by LecrisUT** [comment]
Quick question, by not linking do you mean not running or that the link is not available. Can you `readelf -d` the file and check that it requires the correct link? If it's just about running, than you can overcome it by setting appropriate `INSTALL_RPATH` relative to `$ORIGIN` and installing the missing library files.

**Comment by r1cheu** [comment]
> If it's just about running, than you can overcome it by setting appropriate `INSTALL_RPATH` relative to `$ORIGIN` and installing the missing library files.
You are right!!! but when I use the relative path ${ORIGIN}../../lib, ldd shows that it is linked to libarmadillo.so. However, when importing in Python, it still shows that libarmadillo.so cannot be found, whereas the absolute path works without issue.

**Comment by LecrisUT** [comment]
Well this is a whole design decision that you would need to consider how to tackle. Some points that you should consider:
- Do you want to allow building and linking against pre-installed libraries? Openblas in particular is a tricky one to consider
- If you vendor some of the libraries, where do you want to put them? One convention is to install all your files under `site-packages/my_package`, e.g. you could have installed files as `site-packages/my_package/(lib|include|bin|python_package|...)`
- Where do you want your project to be packaged in, PyPI, conda, spack, distro packaging, etc. Each one of these have some different workflows, but you can focus on designing for PyPI and distro packaging and the rest would be slightly tweaked from there
- Do you want to separate the main C++ library from the python bindings? If so, do you want to export the former as well?

There are slight nuances in how you design the project depending on each of these. It is possible to support the most complicated form of these, but you can also start from a more restrictive form and expand the scope gradually.

**Comment by r1cheu** [comment]
@LecrisUT If I understand correctly:
-  I plan to directly include OpenBLAS in my package， avoiding potential complications from relying on a system-installed version.
- It seems like following the convention of placing it in site-packages/my_package/lib is a good choice.
-  PyPI is sufficient for my situation.
- I expect the C++ library to be separate from the Python bindings, and the C++ library may be compiled into an executable.
Do you have any suggestions? I would be very grateful.

**Comment by r1cheu** [comment]
@LecrisUT Thanks a lot. I should be able to handle these problems.

**Comment by henryiii** [comment]
I should also point out that when you build build redistributable wheels with cibuildwheel, conda-build, etc, those tools run a repair process that bundles in your dependencies.

**Comment by LecrisUT** [comment]
Great, in that case, let's start small.

First let's use all dependencies using `find_package` and build the dependencies withing GH Action. When you run `cibuildwheel` it will call `auditwheel` which bundles all of the necessary dependencies. The caveat here is that windows would not be supported yet. Windows is always a joy to support :face_exhaling:.

<details><summary>About separating C++ and python CMake projects</summary>

You can start by separating the C++ library and the python bindings into 2 projects and try to cover the C++ library building as a standalone, while the python bindings would be covered by a `pip install`/`pytest`. This will make it easier later on to decouple them. Here is a design that I can recommend:

```cmake
# /CMakeLists.txt
project(MainCpp)
option(MAINCPP_PYTHON "MainCpp: Build Python bindings" OFF")

# Main C++ library target
add_library(Main_cpp)
add_library(Main::cpp ALIAS Main_cpp)

if (NOT TARGET Main::python AND MAINCPP_PYTHON)
    add_subdirectory(python)
endif ()
```
```cmake
# /python/CMakeLists.txt
project(MainPython)

# python binding library
add_library(Main_python)
add_library(Main::python ALIAS Main_python)

if (NOT TARGET Main::cpp)
    find_package(MainCpp CONFIG)
    if (NOT MainCpp_FOUND)
        message(STATUS "Using bundled MainCpp sources")
        add_subdirectory(${PROJECT_SOURCE_DIR}/.. _deps/main_cpp-build)
    endif ()
endif ()
```

Here I am assuming some structure of your C++ and python binding targets, but otherwise all namings are arbitrary. For the `pyproject.toml`, point it to `python/CMakeLists.txt` as the main project. Use `tool.scikit-build.wheel.install-dir = "my_project"`.

<details><summary>Explanation of the design</summary>

This makes the project buildable from various directions, from `/CMakeLists.txt` or `/python/CMakeLists.txt`. But as the default that `pip install` will take is:
1. Read `/python/CMakeLists.txt` as the main CMake project
2. Create the python binding target `Main::python`
3. Check if `Main::cpp` target is already defined (this would happen if you build from the main cpp project) -> check fails
4. Try to import `MainCpp` project (you can skip this of course) -> import fails
5. Include the source from the top-level
6. Top-level `CMakeLists.txt` defines the main library `Main::cpp`
7. Python bindings are not re-imported because `Main::python` target is already defined

</details>

From there use the standard design for C++ cmake project, keeping all of the `CMAKE_INSTALL_*` variables as-is. And for the python project do the similar thing like the `scikit_build_example` was doing minus the creating the C++ library. Happy designing, feel free to ping me if things seem weird there.

</details>
