### ISSUE TITLE
Confused about CMAKE_ARGS / SKBUILD_CMAKE_ARGS

### ISSUE THREAD

**Issue by haampie** [scikit-build/scikit-build-core#944]
I don't find the docs very helpful w.r.t. `CMAKE_ARGS` / `SKBUILD_CMAKE_ARGS`, so I'm grepping through the sources.

I found a test that sets `SKBUILD_CMAKE_ARGS` as follows:

```python
monkeypatch.setenv("SKBUILD_CMAKE_ARGS", "-DFOO=BAR;-DBAR=FOO")
```

which gets parsed as

```python
assert settings.cmake.args == ["-DFOO=BAR", "-DBAR=FOO"]
```

but this looks wrong to me, cause `;` is a list separator in CMake. If you pass `cmake '-DFOO=BAR;-DBAR=FOO'` on the command line, CMake defines `FOO` as the list `["BAR", "-DBAR=FOO"]`.

Further, in `scikit-build` the value of `CMAKE_ARGS` was parsed using `shlex.split`, which is necessary to support white space in cmake arguments. When I grep for `shlex.split` in this code base, all I see is

https://github.com/scikit-build/scikit-build-core/blob/bfbd625ac0fb2d1b68b3c7754ed0d1fb1cef0e5e/src/scikit_build_core/builder/builder.py#L112

which is apparently handled separately from SKBUILD_CMAKE_ARGS?

And SKBUILD_CMAKE_ARGS does use `shlex.split`?

1. How am I supposed to pass CMake defines that may contain whitespace in `scikit-build-core`?
2. What's the difference between SKBUILD_CMAKE_ARGS and CMAKE_ARGS?

**Comment by henryiii** [comment]
`CMAKE_ARGS` is modeled after conda-forge and other similar environments which work this way, with space separated values using shlex.split. `SKBUILD_CMAKE_ARGS` is identical to the other `SKBUILD_*` variables that can be used instead of passing `--config-settings` or setting the values in `tool.scikit-build`, and uses `;` as the separator.

The best way to set a define is to use `-Ccmake.define.FOO=BAR -Ccmake.define.BAR=FOO` on the command line.

**Comment by haampie** [comment]
Closing this too early.

Is there a way to pass args in general, not just defines? Say `-Ccmake.arg=--debug-find` etc?

**Comment by henryiii** [comment]
It has an s. `-Ccmake.args=1 -Ccmake.args=2`, etc. It's literally the same thing as SKBUILD_CMAKE_ARGS, every argument can be passed in pyproject.toml, on the command line, or as an environment variable.

**Comment by haampie** [comment]
Thanks, will try
